//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace hospital_sytem
{
    using System;
    using System.Collections.Generic;
    
    public partial class Patient
    {
        public int patientID { get; set; }
        public string patientName { get; set; }
        public string patientStatus { get; set; }
        public Nullable<int> doctorID { get; set; }
    
        public virtual Doctor Doctor { get; set; }
    }
}
